config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'
  get 'error', to: 'pages#error'

  get 'blog', to: redirect('https://github.com/Zardosh')

  resources :projects do
    resources :tasks, except: [:index], controller: 'projects/tasks'
  end

  root 'pages#home'

  get '*path', to: redirect('/error')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/counter.rb
class Counter
    def self.calculate_percent_complete(completed_tasks, total_tasks)
        completed_tasks.to_f / total_tasks.to_f * 100
    end
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :tasks

    after_initialize :set_defaults

    validates_presence_of :title, :description, :percent_complete

    scope :almost_completed, -> { where('percent_complete >= 75.0') }
    scope :still_needs_some_work, -> { where('percent_complete < 75.0') }

    def set_defaults
        self.percent_complete ||= 0.0
    end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  after_save :update_percent_complete if :mark_completed?

  scope :completed, -> { where(completed: true) }

  mount_uploader :task_file, TaskFileUploader

  def mark_completed?
    self.completed == true
  end

  def update_percent_complete
    count_of_completed_tasks = self.project.tasks.completed.count
    count_of_total_tasks = self.project.tasks.count
    
    self.project.update!(percent_complete: Counter.calculate_percent_complete(count_of_completed_tasks, count_of_total_tasks))
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end

  def about
    @title = "Cool Page"
  end

  def home
    @projects = Project.all
  end

  def error
  end
end

app/controllers/projects/tasks_controller.rb
class Projects::TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]
  before_action :set_project, only: %i[ show new edit create update destroy ]
  
  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(task_params)
    @task.project_id = @project.id

    respond_to do |format|
      if @task.save
        format.html { redirect_to project_url(@task.project_id), notice: 'Task was created successfully!' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity } 
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to project_url(@task.project_id), notice: 'Task was updated successfully!' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity } 
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
        format.html { redirect_to project_url(@task.project_id), notice: 'Task was deleted successfully!' }
        format.json { head :no_content }
    end
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    def task_params
      params.require(:task).permit(:title, :description, :project_id, :completed, :task_file)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.still_needs_some_work
  end

  # GET /projects/1 or /projects/1.json
  def show
    @tasks = @project.tasks
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Congratulations! The project was created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "The Project was deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description, :percent_complete)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taski</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <div class="logo">
      <%= image_tag('logos/logo.jpg', width: '150px') %>
    </div>

    <%= render 'shared/nav' %>
    <%= render 'shared/alerts' %>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<hr>
<p><%= @title %></p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/error.html.erb
<h1>Sorry, that page does not exist</h1>

<p>Go back to <%= link_to 'homepage', root_path%></p>

app/views/pages/home.html.erb
<h1>Home page</h1>

<div class="homepage-projects">
    <%= render 'shared/projects' %>
</div>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Title:</strong>
    <%= project.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

  <p>
    <strong>Percent complete:</strong>
    <%= project.percent_complete %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<%= link_to "New project", new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project) %> |
  <%= link_to "Back to projects", projects_path %>

  <%= button_to "Destroy this project", @project, method: :delete %>
</div>

<hr>

<h2>Tasks for project</h2>

<% @tasks.each do |task| %>
  <p><%= link_to task.title, project_task_path(@project.id, task.id) %></p>
<% end %>

<%= link_to "Add a new task for this project", new_project_task_path(project_id: @project.id) %>

app/views/projects/tasks/_form.html.erb
<%= form_for [@project, @task] do |f| %>
    <% if @task.errors.any? %>
      <%= pluralize(@task.errors.count, “error”) %> prohibited this project from being saved:
  
      <% @task.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    <% end %>

    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :description %>
    <%= f.text_area :description %>

    <%= f.label :completed %>
    <%= f.check_box :completed %>

    <%= f.label "Attachment" %>
    <%= f.file_field :task_file %>
    
    <%= f.submit %>
  <% end %>

app/views/projects/tasks/edit.html.erb
<%= render 'form' %>

app/views/projects/tasks/new.html.erb
<%= render 'form' %>

app/views/projects/tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<h3><%= @task.title %></h3>

<p><%= @task.description %></p>
<% if @task.completed %>
    <p><em>Task is completed</em></p>
<% else %>
    <p><em>Task is pending</em></p>
<% end %>

<h4>Task started: <%= @task.created_at %></h4>
<% if @task.created_at != @task.updated_at %>
    <h4>Task updated: <%= @task.updated_at %></h4>
<% end %>

<% unless @task.task_file.blank? %>
    <p><%= link_to "Attachment", @task.task_file.to_s %></p>
<% end %>

<%= link_to "Edit", edit_project_task_path(@task.project_id, @task.id) %>
<%= link_to "Back to project", project_path(@task.project_id) %>

app/views/shared/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_nav.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'Contact', contact_path %>
<%= link_to 'Blog', blog_path %>
<%= link_to 'Projects', projects_path %>

<% if current_user %>
    <%= link_to 'Edit Account', edit_user_registration_path %>
    <%= button_to(
        "Sign Out",
        destroy_user_session_path,
        method: :delete
    ) %>
<% else %>
    <%= link_to "Register", new_user_registration_path %>
    <%= link_to "Sign in", new_user_session_path %>
<% end %>

app/views/shared/_projects.html.erb
<% @projects.each do |project| %>
    <p><strong><%= project.title %></strong> - <em><%= project.description %></em> <%= "| #{project.percent_complete}" if project.percent_complete %></p>
<% end %>